version: '2'
services:
    hopefully-app:
        image: hopefully
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hopefully-mysql:3306/hopefully?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hopefully-elasticsearch:9300
        ports:
            - 8080:8080
    hopefully-mysql:
        extends:
            file: mysql.yml
            service: hopefully-mysql
    hopefully-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hopefully-elasticsearch
